### ISSUE TITLE
Content Hidden!

### ISSUE THREAD

**Issue by forsan** [twotoasters/TWTSideMenuViewController#1]
issue here :)

http://www.youtube.com/watch?v=dqwpuv57Ybs&feature=youtube_gdata_player

**Comment by jnjosh** [comment]
Thanks for the issue.

It is strange though, I'm not seeing that at all. Did you change what the close button does by any chance?

If so, let me know what is changed and I'll track this down.

**Comment by forsan** [comment]
nup nothing change,,, just click fast and it will be happen..

**Comment by jnjosh** [comment]
Hmm. Where is the red view coming from? The sample only displays a tableview.

Are you sure you have the latest?

**Comment by forsan** [comment]
emm i'm very sorry the issue occurred from my changes  :(

im try to change code to be menu with list of controllers and and swipe between these controllers.
