### ISSUE TITLE
Installing via CocoaPods

### ISSUE THREAD

**Issue by chris-garrett** [twotoasters/TWTSideMenuViewController#13]
Is this the correct way to install your library with CocoaPods?

`$ echo "pod 'TWTSideMenuViewController'" >> Podfile`
`$ pod install`
Analyzing dependencies
[!] Unable to find a specification for `TWTSideMenuViewController`.

private repo I guess?
`$ pod repo add TWTSideMenuViewController https://github.com/twotoasters/TWTSideMenuViewController.git`

I query pods and it's showing it now: 
`$ pod list | grep TWT`
  TWTSideMenuViewController
  TWTSideMenuViewController-Sample
  TWTSideMenuViewController-Sample.xcodeproj
  TWTSideMenuViewController-SampleTests

`$ pod install`
[!] Unable to satisfy the following requirements:
- `TWTSideMenuViewController` required by `Podfile`

I'm new to CocoaPods so maybe this is an issue with that.

**Comment by carloabelli** [comment]
I got my Podfile working by inserting the following line:

`pod 'TWTSideMenuViewController', :git => 'https://github.com/twotoasters/TWTSideMenuViewController.git'`

I don't know if this is proper, but it has worked for me.

**Comment by chris-garrett** [comment]
Great! I'll add that to the docs TY

**Comment by tomburns** [comment]
I've submitted a pull request (https://github.com/CocoaPods/Specs/issues/6194) to add TWTSideMenuViewController to the main Cocoapods Specs repo, which should resolve this issue. For now, the above solution should be adequate.

**Comment by tomburns** [comment]
The pull request referenced above has been merged; the pod spec should now be usable without specifying a repository.
