### ISSUE TITLE
iPad Landscape issue

### ISSUE THREAD

**Issue by ghost** [twotoasters/TWTSideMenuViewController#19]
If the app launches in landscape mode on the iPad, when the user navigates to the menu view controller there is a white padding on the sides.  Moving to portrait from landscape and back resolves the issue.
![bug](https://f.cloud.github.com/assets/4582492/2061665/3a16a0a0-8c61-11e3-9775-afc8afd885c1.png)

**Comment by tomburns** [comment]
Thanks, there's a WIP fix for this in #18 that we hope to get merged soon.

**Comment by ghost** [comment]
Ok thanks
